"""id meet creator

Revision ID: f8c4547d4c1c
Revises: edc113a4310c
Create Date: 2023-06-02 15:28:15.880122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c4547d4c1c'
down_revision = 'edc113a4310c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meets', type_='foreignkey')
    op.drop_column('meets', 'user_id')
    # ### end Alembic commands ###
